### ISSUE TITLE
[Feature Request] Use AutoRoute for navigation 

### ISSUE THREAD

**Issue by pongloongyeat** [heickjack619lok/dumbdumb_flutter#7]
As title implies.

## Pros
- We can declaratively state out all routes
- Provides `RouteGuard`s to block access to certain pages (i.e., show login screen to get authentication to blocked page)
- Can inject the `TabsRouter` instance (see #3 ) to switch tabs programatically (without the need to setup a `TabsBloc` or similar)
- Bottom tab bar is always shown be default (requires just a tinyyy bit of work to hide it) but having the option to show it all the time gives quite a lot of flexibility. In addition, the bottom tab bar builder (provided by the `AutoTabsScaffold` widget) runs on each push/pop, meaning we can very easily choose when to hide the bottom tab bar (example implementation included below).
- Deep-linking
- Convenient `context.navigateTo` method to navigate to a certain route by popping the current page if the route being navigated to is the previous page (i.e. no need to check yourself. Handy for VERY nested navigations hint YL is one of them).

## Cons
- Requires `build_runner`. If used with `Freezed` (see #1), this results in a long codegen time (~44s on M1 2020 for YL). This wait time needs to be fully awaited before hot-reloads, hot-restarts or just general builds.
- Setting up default tab bar behaviour (i.e. only shown on root tab page) requires some time

### Example implementation for default tab bar behaviour (i.e. only shown on root tab page)
```dart
@override
Widget build (BuildContext context) {
    return AutoTabsScaffold(
        lazyLoad: false,
        animationDuration: Duration.zero,
        routes: TabsView.tabPages.map((e) => e.route).toList(),
        bottomNavigationBuilder: _buildBottomNavigationBar,
        builder: (_, child, __) => child,
    );
}

Widget _buildBottomNavigationBar(BuildContext context, TabsRouter router) {
    return ExpandedSection(
        expands: _shouldShowBottomNavBar(context.topRoute.name),
        child: BottomNavigationBar(
            currentIndex: router.activeIndex,
            onTap: router.setActiveIndex,
            ...
         ),
    );
}

bool _shouldShowBottomNavBar(String routeName) {
    return routeName == HomeRoute.name || 
           routeName == SearchRoute.name ||
           routeName == NotificationsRoute.name ||
           routeName == ProfileRoute.name;
}
```

**Comment by heickjack619lok** [comment]
Hi @pongloongyeat, Thanks for the suggestion, Nagivator 2.0 is absolutely useful and it is definitely included in the upcoming updates.

**Comment by heickjack619lok** [comment]
supported with Go_Router package #12
